### ISSUE TITLE
Config for routes and user registration

### ISSUE THREAD

**Issue by Diotto6** [Diotto6/fluke-api#1]
We will configure the prism and create the route for creating a user on the platform.

# Task

create the user must have the following fields

- [x] Name: field must be string validating if it is a name
- [x] Password:  field must be string validating if it is a password and encrypted
- [x] FirmPassword:  field must be string validating if it is equal to password and encrypted
- [x] Email: field must be string and unique on the platform validating if it is a email
- [x] Lastname: field must be string validating if it is a lastname
- [x] Birthdate:  field must be date validating if it is a bithdate valid
- [x] isOnline: field must be boolean
- [x] bio: field must be string
